# Generated by Django 5.1 on 2024-09-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acl", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="acl",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="acl",
            constraint=models.UniqueConstraint(
                models.F("service_account"), models.F("zone"), name="unique_acl"
            ),
        ),
    ]
