name: Tests

on:
  pull_request:

jobs:
  django-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r api/requirements.txt

      - name: Run Django tests
        run: |
          cd api
          python3 manage.py test

  build-snap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build snap
        run: |
          snapcraft --verbose
