name: Tests

on:
  pull_request:

jobs:
  django-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r api/requirements.txt

      - name: Run Django tests
        run: |
          cd api
          DJANGO_SECRET_KEY="testkey" python3 manage.py test

  build-snap:
    name: Build snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v22

  snap-tests:
    name: Test the resulting snap
    runs-on: ubuntu-latest
    needs:
      - build-snap
    steps:
      - name: Download snap package(s)
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ needs.build-snap.outputs.artifact-prefix }}-*
          merge-multiple: true

      - name: Build snap
        uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v22

      - name: Install snap
        run: |
          sudo snap install --dangerous charmed-bind_*.snap

      - name: Verify that all services are active
        run: |
          sudo snap services charmed-bind | awk 'NR > 1 && $3 != "active" {exit 1}'

      - name: Check admin interface
        run: |
          curl --retry 5 --retry-delay 10 http://localhost:8080/static/admin/css/base.css
          curl --retry 5 --retry-delay 10 http://localhost:8080/admin/login/
