#!/bin/sh

set -xe

$SNAP/bin/prepare

# Prepare the django database
cd $SNAP_DATA/api
export DJANGO_DATABASE_PATH="$SNAP_COMMON/api/db.sqlite3"
export DJANGO_SECRET_KEY="testkey"
python3 manage.py migrate --noinput
